import 'package:flutter/material.dart';
import 'package:flutter_base_project/design/colors/colors2.dart';

class CRThemes extends ThemeExtension<CRThemes> {
  final Color textGeneralBrand;
  final Color textGreyscale900;
  final Color textGreyscale800;
  final Color textGreyscale700;
  final Color textGreyscale600;
  final Color textGreyscale500;
  final Color textGreyscale400;
  final Color textGreyscale300;
  final Color textGreyscale200;
  final Color textGreyscale100;
  final Color textGreyscale50;
  final Color textGeneralWhite;
  final Color textGeneralBlack;
  final Color textAlertsStatusSuccess;
  final Color textAlertsStatusInfo;
  final Color textAlertsStatusWarning;
  final Color textAlertsStatusError;
  final Color surfaceGeneralBrand;
  final Color surfaceGeneralWhite;
  final Color surfaceGeneralBlack;
  final Color surfaceAlertsStatusSuccess;
  final Color surfaceAlertsStatusInfo;
  final Color surfaceAlertsStatusWarning;
  final Color surfaceAlertsStatusError;
  final Color surfaceAlertsStatusLightDisabled;
  final Color surfaceAlertsStatusDarkDisabled;
  final Color surfaceAlertsStatusButtonDisabled;
  final Color surfaceGreyscale900;
  final Color surfaceGreyscale800;
  final Color surfaceGreyscale700;
  final Color surfaceGreyscale600;
  final Color surfaceGreyscale500;
  final Color surfaceGreyscale400;
  final Color surfaceGreyscale300;
  final Color surfaceGreyscale200;
  final Color surfaceGreyscale100;
  final Color surfaceGreyscale50;
  final Color surfaceLightDarkDark1;
  final Color surfaceLightDarkDark2;
  final Color surfaceLightDarkDark3;
  final Color surfaceLightDarkDark6;
  final Color surfaceLightDarkDark7;
  final Color surfaceBackgroundBackgroundTeal;
  final Color surfaceBackgroundBackgroundPurple;
  final Color surfaceBackgroundBackgroundRed;
  final Color surfaceBackgroundBackgroundBlue;
  final Color surfaceBackgroundBackgroundGreen;
  final Color surfaceBackgroundBackgroundBrown;
  final Color surfaceBackgroundBackgroundYellow;
  final Color surfaceBackgroundBackgroundOrange;
  final Color surfaceTransparentTransparentTeal;
  final Color surfaceTransparentTransparentPurple;
  final Color surfaceTransparentTransparentRed;
  final Color surfaceTransparentTransparentBlue;
  final Color surfaceTransparentTransparentGreen;
  final Color surfaceTransparentTransparentBrown;
  final Color surfaceTransparentTransparentYellow;
  final Color surfaceTransparentTransparentOrange;
  final Color strokeGeneralBrand;
  final Color strokeGreyscaleGreyscale300;
  final Color strokeGreyscaleGreyscale200;
  final Color strokeGreyscaleGreyscale100;
  final Color strokeGreyscaleGreyscale50;
  final Color strokeGeneralWhite;
  final Color strokeGeneralBlack;
  final Color strokeAlertsStatusLightDisabled;
  final Color strokeAlertsStatusDarkDisabled;
  final Color strokeAlertsStatusButtonDisabled;
  final Color strokeGreyscaleGreyscale900;
  final Color strokeGreyscaleGreyscale800;
  final Color strokeGreyscaleGreyscale700;
  final Color strokeGreyscaleGreyscale600;
  final Color strokeGreyscaleGreyscale500;
  final Color strokeGreyscaleGreyscale400;
  final Color strokeAlertsStatusSuccess;
  final Color strokeAlertsStatusInfo;
  final Color strokeAlertsStatusWarning;
  final Color strokeAlertsStatusError;
  final Color strokeBorderSingleStrokeBorderLight;
  final Color strokeBorderFullStrokeLight;
  final Color strokeBorderSingleStrokeDividerLight;
  final Color textButtonsBrand;
  final Color textButtonsWhite;
  final Color textButtonsGreyscale900;
  final Color surfaceButtonsBrand;
  final Color surfaceButtonsButtonLight;
  final Color surfaceButtonsButtonDark;
  final Color surfaceButtonsSocialMediaLight;
  final Color surfaceButtonsSocialMediaDark;
  final Color surfaceButtonsButtonDisabled;
  final Color surfaceButtonsButton50;
  final Color textButtonsSocialMediaLight;
  final Color surfaceButtonsGreyscaleIcon900;
  final Color surfaceButtonsWhiteIcon;
  final Color textButtonsBrandLight;
  final Color textButtonsWhiteDark;
  final Color textButtonsSocialMediaDark;
  final Color surfaceButtonsBrandLight;
  final Color surfaceButtonsWhiteDark;
  final Color strokeBorderSingleStrokeBorderDark;
  final Color strokeBorderSingleStrokeDividerDark;
  final Color strokeBorderFullStrokeDark;
  final Color surfaceComponentsDropdownLight;
  final Color surfaceComponentsDropdownDark;
  final Color surfaceComponentsModalLight;
  final Color surfaceComponentsModalDark;
  final Color surfaceComponentsButtomBarActionLight;
  final Color surfaceComponentsButtomBarActionDark;
  final Color surfaceComponentsGeneralFrameLight;
  final Color surfaceComponentsGeneralFrameDark;
  final Color surfaceAdditionalsOverColorFrameLight;
  final Color surfaceComponentsDropdownIconLight;
  final Color surfaceComponentsDropdownIconDark;
  final Color surfaceLightDarkLight2;
  final Color surfaceLightDarkLight3;
  final Color surfaceLightDarkLight6;
  final Color surfaceLightDarkLight7;
  final Color surfaceLightDarkLight1;
  final Color surfaceAdditionalsOverColorFrameDark;
  final Color textGeneralTextLight;
  final Color textGeneralTextDark;
  final Color surfaceGeneralSurfaceLight;
  final Color surfaceGeneralSurfaceDark;
  final Color surfaceLightDarkLight8;
  final Color surfaceLightDarkDark8;
  final Color strokeAdditionalsToggle400;
  final Color surfaceLightDarkLight5;
  final Color surfaceLightDarkDark5;
  final Color surfaceComponentsSearchSurfaceLight;
  final Color surfaceComponentsSearchSurfaceDark;
  final Color textComponentsSearchTextLight;
  final Color textComponentsSearchTextDark;
  final Color textComponentsTextFilled;
  final Color surfaceComponentsSurfaceFilled;
  final Color strokeLightDarkLight1;
  final Color strokeLightDarkLight2;
  final Color strokeLightDarkLight3;
  final Color strokeLightDarkLight5;
  final Color strokeLightDarkLight4;
  final Color strokeLightDarkLight7;
  final Color strokeLightDarkLight8;
  final Color strokeLightDarkDark1;
  final Color strokeLightDarkDark2;
  final Color strokeLightDarkDark3;
  final Color strokeLightDarkDark5;
  final Color strokeLightDarkDark4;
  final Color strokeLightDarkDark7;
  final Color strokeLightDarkDark8;
  final Color surfaceBackgroundBackgroundGrey;
  final Color surfaceTagSolidDefaultGrey600;
  final Color surfaceTagInvertedDefaultLight;
  final Color surfaceTagInvertedInfoLight;
  final Color surfaceTagInvertedSuccessLight;
  final Color surfaceTagInvertedWarningLight;
  final Color surfaceTagInvertedErrorLight;

  const CRThemes({
    required this.textGeneralBrand,
    required this.textGreyscale900,
    required this.textGreyscale800,
    required this.textGreyscale700,
    required this.textGreyscale600,
    required this.textGreyscale500,
    required this.textGreyscale400,
    required this.textGreyscale300,
    required this.textGreyscale200,
    required this.textGreyscale100,
    required this.textGreyscale50,
    required this.textGeneralWhite,
    required this.textGeneralBlack,
    required this.textAlertsStatusSuccess,
    required this.textAlertsStatusInfo,
    required this.textAlertsStatusWarning,
    required this.textAlertsStatusError,
    required this.surfaceGeneralBrand,
    required this.surfaceGeneralWhite,
    required this.surfaceGeneralBlack,
    required this.surfaceAlertsStatusSuccess,
    required this.surfaceAlertsStatusInfo,
    required this.surfaceAlertsStatusWarning,
    required this.surfaceAlertsStatusError,
    required this.surfaceAlertsStatusLightDisabled,
    required this.surfaceAlertsStatusDarkDisabled,
    required this.surfaceAlertsStatusButtonDisabled,
    required this.surfaceGreyscale900,
    required this.surfaceGreyscale800,
    required this.surfaceGreyscale700,
    required this.surfaceGreyscale600,
    required this.surfaceGreyscale500,
    required this.surfaceGreyscale400,
    required this.surfaceGreyscale300,
    required this.surfaceGreyscale200,
    required this.surfaceGreyscale100,
    required this.surfaceGreyscale50,
    required this.surfaceLightDarkDark1,
    required this.surfaceLightDarkDark2,
    required this.surfaceLightDarkDark3,
    required this.surfaceLightDarkDark6,
    required this.surfaceLightDarkDark7,
    required this.surfaceBackgroundBackgroundTeal,
    required this.surfaceBackgroundBackgroundPurple,
    required this.surfaceBackgroundBackgroundRed,
    required this.surfaceBackgroundBackgroundBlue,
    required this.surfaceBackgroundBackgroundGreen,
    required this.surfaceBackgroundBackgroundBrown,
    required this.surfaceBackgroundBackgroundYellow,
    required this.surfaceBackgroundBackgroundOrange,
    required this.surfaceTransparentTransparentTeal,
    required this.surfaceTransparentTransparentPurple,
    required this.surfaceTransparentTransparentRed,
    required this.surfaceTransparentTransparentBlue,
    required this.surfaceTransparentTransparentGreen,
    required this.surfaceTransparentTransparentBrown,
    required this.surfaceTransparentTransparentYellow,
    required this.surfaceTransparentTransparentOrange,
    required this.strokeGeneralBrand,
    required this.strokeGreyscaleGreyscale300,
    required this.strokeGreyscaleGreyscale200,
    required this.strokeGreyscaleGreyscale100,
    required this.strokeGreyscaleGreyscale50,
    required this.strokeGeneralWhite,
    required this.strokeGeneralBlack,
    required this.strokeAlertsStatusLightDisabled,
    required this.strokeAlertsStatusDarkDisabled,
    required this.strokeAlertsStatusButtonDisabled,
    required this.strokeGreyscaleGreyscale900,
    required this.strokeGreyscaleGreyscale800,
    required this.strokeGreyscaleGreyscale700,
    required this.strokeGreyscaleGreyscale600,
    required this.strokeGreyscaleGreyscale500,
    required this.strokeGreyscaleGreyscale400,
    required this.strokeAlertsStatusSuccess,
    required this.strokeAlertsStatusInfo,
    required this.strokeAlertsStatusWarning,
    required this.strokeAlertsStatusError,
    required this.strokeBorderSingleStrokeBorderLight,
    required this.strokeBorderFullStrokeLight,
    required this.strokeBorderSingleStrokeDividerLight,
    required this.textButtonsBrand,
    required this.textButtonsWhite,
    required this.textButtonsGreyscale900,
    required this.surfaceButtonsBrand,
    required this.surfaceButtonsButtonLight,
    required this.surfaceButtonsButtonDark,
    required this.surfaceButtonsSocialMediaLight,
    required this.surfaceButtonsSocialMediaDark,
    required this.surfaceButtonsButtonDisabled,
    required this.surfaceButtonsButton50,
    required this.textButtonsSocialMediaLight,
    required this.surfaceButtonsGreyscaleIcon900,
    required this.surfaceButtonsWhiteIcon,
    required this.textButtonsBrandLight,
    required this.textButtonsWhiteDark,
    required this.textButtonsSocialMediaDark,
    required this.surfaceButtonsBrandLight,
    required this.surfaceButtonsWhiteDark,
    required this.strokeBorderSingleStrokeBorderDark,
    required this.strokeBorderSingleStrokeDividerDark,
    required this.strokeBorderFullStrokeDark,
    required this.surfaceComponentsDropdownLight,
    required this.surfaceComponentsDropdownDark,
    required this.surfaceComponentsModalLight,
    required this.surfaceComponentsModalDark,
    required this.surfaceComponentsButtomBarActionLight,
    required this.surfaceComponentsButtomBarActionDark,
    required this.surfaceComponentsGeneralFrameLight,
    required this.surfaceComponentsGeneralFrameDark,
    required this.surfaceAdditionalsOverColorFrameLight,
    required this.surfaceComponentsDropdownIconLight,
    required this.surfaceComponentsDropdownIconDark,
    required this.surfaceLightDarkLight2,
    required this.surfaceLightDarkLight3,
    required this.surfaceLightDarkLight6,
    required this.surfaceLightDarkLight7,
    required this.surfaceLightDarkLight1,
    required this.surfaceAdditionalsOverColorFrameDark,
    required this.textGeneralTextLight,
    required this.textGeneralTextDark,
    required this.surfaceGeneralSurfaceLight,
    required this.surfaceGeneralSurfaceDark,
    required this.surfaceLightDarkLight8,
    required this.surfaceLightDarkDark8,
    required this.strokeAdditionalsToggle400,
    required this.surfaceLightDarkLight5,
    required this.surfaceLightDarkDark5,
    required this.surfaceComponentsSearchSurfaceLight,
    required this.surfaceComponentsSearchSurfaceDark,
    required this.textComponentsSearchTextLight,
    required this.textComponentsSearchTextDark,
    required this.textComponentsTextFilled,
    required this.surfaceComponentsSurfaceFilled,
    required this.strokeLightDarkLight1,
    required this.strokeLightDarkLight2,
    required this.strokeLightDarkLight3,
    required this.strokeLightDarkLight5,
    required this.strokeLightDarkLight4,
    required this.strokeLightDarkLight7,
    required this.strokeLightDarkLight8,
    required this.strokeLightDarkDark1,
    required this.strokeLightDarkDark2,
    required this.strokeLightDarkDark3,
    required this.strokeLightDarkDark5,
    required this.strokeLightDarkDark4,
    required this.strokeLightDarkDark7,
    required this.strokeLightDarkDark8,
    required this.surfaceBackgroundBackgroundGrey,
    required this.surfaceTagSolidDefaultGrey600,
    required this.surfaceTagInvertedDefaultLight,
    required this.surfaceTagInvertedInfoLight,
    required this.surfaceTagInvertedSuccessLight,
    required this.surfaceTagInvertedWarningLight,
    required this.surfaceTagInvertedErrorLight,
  });

  factory CRThemes.light() {
    return CRThemes(
      textGeneralBrand: CRColors2.textGeneralBrand.light,
      textGreyscale900: CRColors2.textGreyscale900.light,
      textGreyscale800: CRColors2.textGreyscale800.light,
      textGreyscale700: CRColors2.textGreyscale700.light,
      textGreyscale600: CRColors2.textGreyscale600.light,
      textGreyscale500: CRColors2.textGreyscale500.light,
      textGreyscale400: CRColors2.textGreyscale400.light,
      textGreyscale300: CRColors2.textGreyscale300.light,
      textGreyscale200: CRColors2.textGreyscale200.light,
      textGreyscale100: CRColors2.textGreyscale100.light,
      textGreyscale50: CRColors2.textGreyscale50.light,
      textGeneralWhite: CRColors2.textGeneralWhite.light,
      textGeneralBlack: CRColors2.textGeneralBlack.light,
      textAlertsStatusSuccess: CRColors2.textAlertsStatusSuccess.light,
      textAlertsStatusInfo: CRColors2.textAlertsStatusInfo.light,
      textAlertsStatusWarning: CRColors2.textAlertsStatusWarning.light,
      textAlertsStatusError: CRColors2.textAlertsStatusError.light,
      surfaceGeneralBrand: CRColors2.surfaceGeneralBrand.light,
      surfaceGeneralWhite: CRColors2.surfaceGeneralWhite.light,
      surfaceGeneralBlack: CRColors2.surfaceGeneralBlack.light,
      surfaceAlertsStatusSuccess: CRColors2.surfaceAlertsStatusSuccess.light,
      surfaceAlertsStatusInfo: CRColors2.surfaceAlertsStatusInfo.light,
      surfaceAlertsStatusWarning: CRColors2.surfaceAlertsStatusWarning.light,
      surfaceAlertsStatusError: CRColors2.surfaceAlertsStatusError.light,
      surfaceAlertsStatusLightDisabled: CRColors2.surfaceAlertsStatusLightDisabled.light,
      surfaceAlertsStatusDarkDisabled: CRColors2.surfaceAlertsStatusDarkDisabled.light,
      surfaceAlertsStatusButtonDisabled: CRColors2.surfaceAlertsStatusButtonDisabled.light,
      surfaceGreyscale900: CRColors2.surfaceGreyscale900.light,
      surfaceGreyscale800: CRColors2.surfaceGreyscale800.light,
      surfaceGreyscale700: CRColors2.surfaceGreyscale700.light,
      surfaceGreyscale600: CRColors2.surfaceGreyscale600.light,
      surfaceGreyscale500: CRColors2.surfaceGreyscale500.light,
      surfaceGreyscale400: CRColors2.surfaceGreyscale400.light,
      surfaceGreyscale300: CRColors2.surfaceGreyscale300.light,
      surfaceGreyscale200: CRColors2.surfaceGreyscale200.light,
      surfaceGreyscale100: CRColors2.surfaceGreyscale100.light,
      surfaceGreyscale50: CRColors2.surfaceGreyscale50.light,
      surfaceLightDarkDark1: CRColors2.surfaceLightDarkDark1.light,
      surfaceLightDarkDark2: CRColors2.surfaceLightDarkDark2.light,
      surfaceLightDarkDark3: CRColors2.surfaceLightDarkDark3.light,
      surfaceLightDarkDark6: CRColors2.surfaceLightDarkDark6.light,
      surfaceLightDarkDark7: CRColors2.surfaceLightDarkDark7.light,
      surfaceBackgroundBackgroundTeal: CRColors2.surfaceBackgroundBackgroundTeal.light,
      surfaceBackgroundBackgroundPurple: CRColors2.surfaceBackgroundBackgroundPurple.light,
      surfaceBackgroundBackgroundRed: CRColors2.surfaceBackgroundBackgroundRed.light,
      surfaceBackgroundBackgroundBlue: CRColors2.surfaceBackgroundBackgroundBlue.light,
      surfaceBackgroundBackgroundGreen: CRColors2.surfaceBackgroundBackgroundGreen.light,
      surfaceBackgroundBackgroundBrown: CRColors2.surfaceBackgroundBackgroundBrown.light,
      surfaceBackgroundBackgroundYellow: CRColors2.surfaceBackgroundBackgroundYellow.light,
      surfaceBackgroundBackgroundOrange: CRColors2.surfaceBackgroundBackgroundOrange.light,
      surfaceTransparentTransparentTeal: CRColors2.surfaceTransparentTransparentTeal.light,
      surfaceTransparentTransparentPurple: CRColors2.surfaceTransparentTransparentPurple.light,
      surfaceTransparentTransparentRed: CRColors2.surfaceTransparentTransparentRed.light,
      surfaceTransparentTransparentBlue: CRColors2.surfaceTransparentTransparentBlue.light,
      surfaceTransparentTransparentGreen: CRColors2.surfaceTransparentTransparentGreen.light,
      surfaceTransparentTransparentBrown: CRColors2.surfaceTransparentTransparentBrown.light,
      surfaceTransparentTransparentYellow: CRColors2.surfaceTransparentTransparentYellow.light,
      surfaceTransparentTransparentOrange: CRColors2.surfaceTransparentTransparentOrange.light,
      strokeGeneralBrand: CRColors2.strokeGeneralBrand.light,
      strokeGreyscaleGreyscale300: CRColors2.strokeGreyscaleGreyscale300.light,
      strokeGreyscaleGreyscale200: CRColors2.strokeGreyscaleGreyscale200.light,
      strokeGreyscaleGreyscale100: CRColors2.strokeGreyscaleGreyscale100.light,
      strokeGreyscaleGreyscale50: CRColors2.strokeGreyscaleGreyscale50.light,
      strokeGeneralWhite: CRColors2.strokeGeneralWhite.light,
      strokeGeneralBlack: CRColors2.strokeGeneralBlack.light,
      strokeAlertsStatusLightDisabled: CRColors2.strokeAlertsStatusLightDisabled.light,
      strokeAlertsStatusDarkDisabled: CRColors2.strokeAlertsStatusDarkDisabled.light,
      strokeAlertsStatusButtonDisabled: CRColors2.strokeAlertsStatusButtonDisabled.light,
      strokeGreyscaleGreyscale900: CRColors2.strokeGreyscaleGreyscale900.light,
      strokeGreyscaleGreyscale800: CRColors2.strokeGreyscaleGreyscale800.light,
      strokeGreyscaleGreyscale700: CRColors2.strokeGreyscaleGreyscale700.light,
      strokeGreyscaleGreyscale600: CRColors2.strokeGreyscaleGreyscale600.light,
      strokeGreyscaleGreyscale500: CRColors2.strokeGreyscaleGreyscale500.light,
      strokeGreyscaleGreyscale400: CRColors2.strokeGreyscaleGreyscale400.light,
      strokeAlertsStatusSuccess: CRColors2.strokeAlertsStatusSuccess.light,
      strokeAlertsStatusInfo: CRColors2.strokeAlertsStatusInfo.light,
      strokeAlertsStatusWarning: CRColors2.strokeAlertsStatusWarning.light,
      strokeAlertsStatusError: CRColors2.strokeAlertsStatusError.light,
      strokeBorderSingleStrokeBorderLight: CRColors2.strokeBorderSingleStrokeBorderLight.light,
      strokeBorderFullStrokeLight: CRColors2.strokeBorderFullStrokeLight.light,
      strokeBorderSingleStrokeDividerLight: CRColors2.strokeBorderSingleStrokeDividerLight.light,
      textButtonsBrand: CRColors2.textButtonsBrand.light,
      textButtonsWhite: CRColors2.textButtonsWhite.light,
      textButtonsGreyscale900: CRColors2.textButtonsGreyscale900.light,
      surfaceButtonsBrand: CRColors2.surfaceButtonsBrand.light,
      surfaceButtonsButtonLight: CRColors2.surfaceButtonsButtonLight.light,
      surfaceButtonsButtonDark: CRColors2.surfaceButtonsButtonDark.light,
      surfaceButtonsSocialMediaLight: CRColors2.surfaceButtonsSocialMediaLight.light,
      surfaceButtonsSocialMediaDark: CRColors2.surfaceButtonsSocialMediaDark.light,
      surfaceButtonsButtonDisabled: CRColors2.surfaceButtonsButtonDisabled.light,
      surfaceButtonsButton50: CRColors2.surfaceButtonsButton50.light,
      textButtonsSocialMediaLight: CRColors2.textButtonsSocialMediaLight.light,
      surfaceButtonsGreyscaleIcon900: CRColors2.surfaceButtonsGreyscaleIcon900.light,
      surfaceButtonsWhiteIcon: CRColors2.surfaceButtonsWhiteIcon.light,
      textButtonsBrandLight: CRColors2.textButtonsBrandLight.light,
      textButtonsWhiteDark: CRColors2.textButtonsWhiteDark.light,
      textButtonsSocialMediaDark: CRColors2.textButtonsSocialMediaDark.light,
      surfaceButtonsBrandLight: CRColors2.surfaceButtonsBrandLight.light,
      surfaceButtonsWhiteDark: CRColors2.surfaceButtonsWhiteDark.light,
      strokeBorderSingleStrokeBorderDark: CRColors2.strokeBorderSingleStrokeBorderDark.light,
      strokeBorderSingleStrokeDividerDark: CRColors2.strokeBorderSingleStrokeDividerDark.light,
      strokeBorderFullStrokeDark: CRColors2.strokeBorderFullStrokeDark.light,
      surfaceComponentsDropdownLight: CRColors2.surfaceComponentsDropdownLight.light,
      surfaceComponentsDropdownDark: CRColors2.surfaceComponentsDropdownDark.light,
      surfaceComponentsModalLight: CRColors2.surfaceComponentsModalLight.light,
      surfaceComponentsModalDark: CRColors2.surfaceComponentsModalDark.light,
      surfaceComponentsButtomBarActionLight: CRColors2.surfaceComponentsButtomBarActionLight.light,
      surfaceComponentsButtomBarActionDark: CRColors2.surfaceComponentsButtomBarActionDark.light,
      surfaceComponentsGeneralFrameLight: CRColors2.surfaceComponentsGeneralFrameLight.light,
      surfaceComponentsGeneralFrameDark: CRColors2.surfaceComponentsGeneralFrameDark.light,
      surfaceAdditionalsOverColorFrameLight: CRColors2.surfaceAdditionalsOverColorFrameLight.light,
      surfaceComponentsDropdownIconLight: CRColors2.surfaceComponentsDropdownIconLight.light,
      surfaceComponentsDropdownIconDark: CRColors2.surfaceComponentsDropdownIconDark.light,
      surfaceLightDarkLight2: CRColors2.surfaceLightDarkLight2.light,
      surfaceLightDarkLight3: CRColors2.surfaceLightDarkLight3.light,
      surfaceLightDarkLight6: CRColors2.surfaceLightDarkLight6.light,
      surfaceLightDarkLight7: CRColors2.surfaceLightDarkLight7.light,
      surfaceLightDarkLight1: CRColors2.surfaceLightDarkLight1.light,
      surfaceAdditionalsOverColorFrameDark: CRColors2.surfaceAdditionalsOverColorFrameDark.light,
      textGeneralTextLight: CRColors2.textGeneralTextLight.light,
      textGeneralTextDark: CRColors2.textGeneralTextDark.light,
      surfaceGeneralSurfaceLight: CRColors2.surfaceGeneralSurfaceLight.light,
      surfaceGeneralSurfaceDark: CRColors2.surfaceGeneralSurfaceDark.light,
      surfaceLightDarkLight8: CRColors2.surfaceLightDarkLight8.light,
      surfaceLightDarkDark8: CRColors2.surfaceLightDarkDark8.light,
      strokeAdditionalsToggle400: CRColors2.strokeAdditionalsToggle400.light,
      surfaceLightDarkLight5: CRColors2.surfaceLightDarkLight5.light,
      surfaceLightDarkDark5: CRColors2.surfaceLightDarkDark5.light,
      surfaceComponentsSearchSurfaceLight: CRColors2.surfaceComponentsSearchSurfaceLight.light,
      surfaceComponentsSearchSurfaceDark: CRColors2.surfaceComponentsSearchSurfaceDark.light,
      textComponentsSearchTextLight: CRColors2.textComponentsSearchTextLight.light,
      textComponentsSearchTextDark: CRColors2.textComponentsSearchTextDark.light,
      textComponentsTextFilled: CRColors2.textComponentsTextFilled.light,
      surfaceComponentsSurfaceFilled: CRColors2.surfaceComponentsSurfaceFilled.light,
      strokeLightDarkLight1: CRColors2.strokeLightDarkLight1.light,
      strokeLightDarkLight2: CRColors2.strokeLightDarkLight2.light,
      strokeLightDarkLight3: CRColors2.strokeLightDarkLight3.light,
      strokeLightDarkLight5: CRColors2.strokeLightDarkLight5.light,
      strokeLightDarkLight4: CRColors2.strokeLightDarkLight4.light,
      strokeLightDarkLight7: CRColors2.strokeLightDarkLight7.light,
      strokeLightDarkLight8: CRColors2.strokeLightDarkLight8.light,
      strokeLightDarkDark1: CRColors2.strokeLightDarkDark1.light,
      strokeLightDarkDark2: CRColors2.strokeLightDarkDark2.light,
      strokeLightDarkDark3: CRColors2.strokeLightDarkDark3.light,
      strokeLightDarkDark5: CRColors2.strokeLightDarkDark5.light,
      strokeLightDarkDark4: CRColors2.strokeLightDarkDark4.light,
      strokeLightDarkDark7: CRColors2.strokeLightDarkDark7.light,
      strokeLightDarkDark8: CRColors2.strokeLightDarkDark8.light,
      surfaceBackgroundBackgroundGrey: CRColors2.surfaceBackgroundBackgroundGrey.light,
      surfaceTagSolidDefaultGrey600: CRColors2.surfaceTagSolidDefaultGrey600.light,
      surfaceTagInvertedDefaultLight: CRColors2.surfaceTagInvertedDefaultLight.light,
      surfaceTagInvertedInfoLight: CRColors2.surfaceTagInvertedInfoLight.light,
      surfaceTagInvertedSuccessLight: CRColors2.surfaceTagInvertedSuccessLight.light,
      surfaceTagInvertedWarningLight: CRColors2.surfaceTagInvertedWarningLight.light,
      surfaceTagInvertedErrorLight: CRColors2.surfaceTagInvertedErrorLight.light,
    );
  }

  factory CRThemes.dark() {
    return CRThemes(
      textGeneralBrand: CRColors2.textGeneralBrand.dark,
      textGreyscale900: CRColors2.textGreyscale900.dark,
      textGreyscale800: CRColors2.textGreyscale800.dark,
      textGreyscale700: CRColors2.textGreyscale700.dark,
      textGreyscale600: CRColors2.textGreyscale600.dark,
      textGreyscale500: CRColors2.textGreyscale500.dark,
      textGreyscale400: CRColors2.textGreyscale400.dark,
      textGreyscale300: CRColors2.textGreyscale300.dark,
      textGreyscale200: CRColors2.textGreyscale200.dark,
      textGreyscale100: CRColors2.textGreyscale100.dark,
      textGreyscale50: CRColors2.textGreyscale50.dark,
      textGeneralWhite: CRColors2.textGeneralWhite.dark,
      textGeneralBlack: CRColors2.textGeneralBlack.dark,
      textAlertsStatusSuccess: CRColors2.textAlertsStatusSuccess.dark,
      textAlertsStatusInfo: CRColors2.textAlertsStatusInfo.dark,
      textAlertsStatusWarning: CRColors2.textAlertsStatusWarning.dark,
      textAlertsStatusError: CRColors2.textAlertsStatusError.dark,
      surfaceGeneralBrand: CRColors2.surfaceGeneralBrand.dark,
      surfaceGeneralWhite: CRColors2.surfaceGeneralWhite.dark,
      surfaceGeneralBlack: CRColors2.surfaceGeneralBlack.dark,
      surfaceAlertsStatusSuccess: CRColors2.surfaceAlertsStatusSuccess.dark,
      surfaceAlertsStatusInfo: CRColors2.surfaceAlertsStatusInfo.dark,
      surfaceAlertsStatusWarning: CRColors2.surfaceAlertsStatusWarning.dark,
      surfaceAlertsStatusError: CRColors2.surfaceAlertsStatusError.dark,
      surfaceAlertsStatusLightDisabled: CRColors2.surfaceAlertsStatusLightDisabled.dark,
      surfaceAlertsStatusDarkDisabled: CRColors2.surfaceAlertsStatusDarkDisabled.dark,
      surfaceAlertsStatusButtonDisabled: CRColors2.surfaceAlertsStatusButtonDisabled.dark,
      surfaceGreyscale900: CRColors2.surfaceGreyscale900.dark,
      surfaceGreyscale800: CRColors2.surfaceGreyscale800.dark,
      surfaceGreyscale700: CRColors2.surfaceGreyscale700.dark,
      surfaceGreyscale600: CRColors2.surfaceGreyscale600.dark,
      surfaceGreyscale500: CRColors2.surfaceGreyscale500.dark,
      surfaceGreyscale400: CRColors2.surfaceGreyscale400.dark,
      surfaceGreyscale300: CRColors2.surfaceGreyscale300.dark,
      surfaceGreyscale200: CRColors2.surfaceGreyscale200.dark,
      surfaceGreyscale100: CRColors2.surfaceGreyscale100.dark,
      surfaceGreyscale50: CRColors2.surfaceGreyscale50.dark,
      surfaceLightDarkDark1: CRColors2.surfaceLightDarkDark1.dark,
      surfaceLightDarkDark2: CRColors2.surfaceLightDarkDark2.dark,
      surfaceLightDarkDark3: CRColors2.surfaceLightDarkDark3.dark,
      surfaceLightDarkDark6: CRColors2.surfaceLightDarkDark6.dark,
      surfaceLightDarkDark7: CRColors2.surfaceLightDarkDark7.dark,
      surfaceBackgroundBackgroundTeal: CRColors2.surfaceBackgroundBackgroundTeal.dark,
      surfaceBackgroundBackgroundPurple: CRColors2.surfaceBackgroundBackgroundPurple.dark,
      surfaceBackgroundBackgroundRed: CRColors2.surfaceBackgroundBackgroundRed.dark,
      surfaceBackgroundBackgroundBlue: CRColors2.surfaceBackgroundBackgroundBlue.dark,
      surfaceBackgroundBackgroundGreen: CRColors2.surfaceBackgroundBackgroundGreen.dark,
      surfaceBackgroundBackgroundBrown: CRColors2.surfaceBackgroundBackgroundBrown.dark,
      surfaceBackgroundBackgroundYellow: CRColors2.surfaceBackgroundBackgroundYellow.dark,
      surfaceBackgroundBackgroundOrange: CRColors2.surfaceBackgroundBackgroundOrange.dark,
      surfaceTransparentTransparentTeal: CRColors2.surfaceTransparentTransparentTeal.dark,
      surfaceTransparentTransparentPurple: CRColors2.surfaceTransparentTransparentPurple.dark,
      surfaceTransparentTransparentRed: CRColors2.surfaceTransparentTransparentRed.dark,
      surfaceTransparentTransparentBlue: CRColors2.surfaceTransparentTransparentBlue.dark,
      surfaceTransparentTransparentGreen: CRColors2.surfaceTransparentTransparentGreen.dark,
      surfaceTransparentTransparentBrown: CRColors2.surfaceTransparentTransparentBrown.dark,
      surfaceTransparentTransparentYellow: CRColors2.surfaceTransparentTransparentYellow.dark,
      surfaceTransparentTransparentOrange: CRColors2.surfaceTransparentTransparentOrange.dark,
      strokeGeneralBrand: CRColors2.strokeGeneralBrand.dark,
      strokeGreyscaleGreyscale300: CRColors2.strokeGreyscaleGreyscale300.dark,
      strokeGreyscaleGreyscale200: CRColors2.strokeGreyscaleGreyscale200.dark,
      strokeGreyscaleGreyscale100: CRColors2.strokeGreyscaleGreyscale100.dark,
      strokeGreyscaleGreyscale50: CRColors2.strokeGreyscaleGreyscale50.dark,
      strokeGeneralWhite: CRColors2.strokeGeneralWhite.dark,
      strokeGeneralBlack: CRColors2.strokeGeneralBlack.dark,
      strokeAlertsStatusLightDisabled: CRColors2.strokeAlertsStatusLightDisabled.dark,
      strokeAlertsStatusDarkDisabled: CRColors2.strokeAlertsStatusDarkDisabled.dark,
      strokeAlertsStatusButtonDisabled: CRColors2.strokeAlertsStatusButtonDisabled.dark,
      strokeGreyscaleGreyscale900: CRColors2.strokeGreyscaleGreyscale900.dark,
      strokeGreyscaleGreyscale800: CRColors2.strokeGreyscaleGreyscale800.dark,
      strokeGreyscaleGreyscale700: CRColors2.strokeGreyscaleGreyscale700.dark,
      strokeGreyscaleGreyscale600: CRColors2.strokeGreyscaleGreyscale600.dark,
      strokeGreyscaleGreyscale500: CRColors2.strokeGreyscaleGreyscale500.dark,
      strokeGreyscaleGreyscale400: CRColors2.strokeGreyscaleGreyscale400.dark,
      strokeAlertsStatusSuccess: CRColors2.strokeAlertsStatusSuccess.dark,
      strokeAlertsStatusInfo: CRColors2.strokeAlertsStatusInfo.dark,
      strokeAlertsStatusWarning: CRColors2.strokeAlertsStatusWarning.dark,
      strokeAlertsStatusError: CRColors2.strokeAlertsStatusError.dark,
      strokeBorderSingleStrokeBorderLight: CRColors2.strokeBorderSingleStrokeBorderLight.dark,
      strokeBorderFullStrokeLight: CRColors2.strokeBorderFullStrokeLight.dark,
      strokeBorderSingleStrokeDividerLight: CRColors2.strokeBorderSingleStrokeDividerLight.dark,
      textButtonsBrand: CRColors2.textButtonsBrand.dark,
      textButtonsWhite: CRColors2.textButtonsWhite.dark,
      textButtonsGreyscale900: CRColors2.textButtonsGreyscale900.dark,
      surfaceButtonsBrand: CRColors2.surfaceButtonsBrand.dark,
      surfaceButtonsButtonLight: CRColors2.surfaceButtonsButtonLight.dark,
      surfaceButtonsButtonDark: CRColors2.surfaceButtonsButtonDark.dark,
      surfaceButtonsSocialMediaLight: CRColors2.surfaceButtonsSocialMediaLight.dark,
      surfaceButtonsSocialMediaDark: CRColors2.surfaceButtonsSocialMediaDark.dark,
      surfaceButtonsButtonDisabled: CRColors2.surfaceButtonsButtonDisabled.dark,
      surfaceButtonsButton50: CRColors2.surfaceButtonsButton50.dark,
      textButtonsSocialMediaLight: CRColors2.textButtonsSocialMediaLight.dark,
      surfaceButtonsGreyscaleIcon900: CRColors2.surfaceButtonsGreyscaleIcon900.dark,
      surfaceButtonsWhiteIcon: CRColors2.surfaceButtonsWhiteIcon.dark,
      textButtonsBrandLight: CRColors2.textButtonsBrandLight.dark,
      textButtonsWhiteDark: CRColors2.textButtonsWhiteDark.dark,
      textButtonsSocialMediaDark: CRColors2.textButtonsSocialMediaDark.dark,
      surfaceButtonsBrandLight: CRColors2.surfaceButtonsBrandLight.dark,
      surfaceButtonsWhiteDark: CRColors2.surfaceButtonsWhiteDark.dark,
      strokeBorderSingleStrokeBorderDark: CRColors2.strokeBorderSingleStrokeBorderDark.dark,
      strokeBorderSingleStrokeDividerDark: CRColors2.strokeBorderSingleStrokeDividerDark.dark,
      strokeBorderFullStrokeDark: CRColors2.strokeBorderFullStrokeDark.dark,
      surfaceComponentsDropdownLight: CRColors2.surfaceComponentsDropdownLight.dark,
      surfaceComponentsDropdownDark: CRColors2.surfaceComponentsDropdownDark.dark,
      surfaceComponentsModalLight: CRColors2.surfaceComponentsModalLight.dark,
      surfaceComponentsModalDark: CRColors2.surfaceComponentsModalDark.dark,
      surfaceComponentsButtomBarActionLight: CRColors2.surfaceComponentsButtomBarActionLight.dark,
      surfaceComponentsButtomBarActionDark: CRColors2.surfaceComponentsButtomBarActionDark.dark,
      surfaceComponentsGeneralFrameLight: CRColors2.surfaceComponentsGeneralFrameLight.dark,
      surfaceComponentsGeneralFrameDark: CRColors2.surfaceComponentsGeneralFrameDark.dark,
      surfaceAdditionalsOverColorFrameLight: CRColors2.surfaceAdditionalsOverColorFrameLight.dark,
      surfaceComponentsDropdownIconLight: CRColors2.surfaceComponentsDropdownIconLight.dark,
      surfaceComponentsDropdownIconDark: CRColors2.surfaceComponentsDropdownIconDark.dark,
      surfaceLightDarkLight2: CRColors2.surfaceLightDarkLight2.dark,
      surfaceLightDarkLight3: CRColors2.surfaceLightDarkLight3.dark,
      surfaceLightDarkLight6: CRColors2.surfaceLightDarkLight6.dark,
      surfaceLightDarkLight7: CRColors2.surfaceLightDarkLight7.dark,
      surfaceLightDarkLight1: CRColors2.surfaceLightDarkLight1.dark,
      surfaceAdditionalsOverColorFrameDark: CRColors2.surfaceAdditionalsOverColorFrameDark.dark,
      textGeneralTextLight: CRColors2.textGeneralTextLight.dark,
      textGeneralTextDark: CRColors2.textGeneralTextDark.dark,
      surfaceGeneralSurfaceLight: CRColors2.surfaceGeneralSurfaceLight.dark,
      surfaceGeneralSurfaceDark: CRColors2.surfaceGeneralSurfaceDark.dark,
      surfaceLightDarkLight8: CRColors2.surfaceLightDarkLight8.dark,
      surfaceLightDarkDark8: CRColors2.surfaceLightDarkDark8.dark,
      strokeAdditionalsToggle400: CRColors2.strokeAdditionalsToggle400.dark,
      surfaceLightDarkLight5: CRColors2.surfaceLightDarkLight5.dark,
      surfaceLightDarkDark5: CRColors2.surfaceLightDarkDark5.dark,
      surfaceComponentsSearchSurfaceLight: CRColors2.surfaceComponentsSearchSurfaceLight.dark,
      surfaceComponentsSearchSurfaceDark: CRColors2.surfaceComponentsSearchSurfaceDark.dark,
      textComponentsSearchTextLight: CRColors2.textComponentsSearchTextLight.dark,
      textComponentsSearchTextDark: CRColors2.textComponentsSearchTextDark.dark,
      textComponentsTextFilled: CRColors2.textComponentsTextFilled.dark,
      surfaceComponentsSurfaceFilled: CRColors2.surfaceComponentsSurfaceFilled.dark,
      strokeLightDarkLight1: CRColors2.strokeLightDarkLight1.dark,
      strokeLightDarkLight2: CRColors2.strokeLightDarkLight2.dark,
      strokeLightDarkLight3: CRColors2.strokeLightDarkLight3.dark,
      strokeLightDarkLight5: CRColors2.strokeLightDarkLight5.dark,
      strokeLightDarkLight4: CRColors2.strokeLightDarkLight4.dark,
      strokeLightDarkLight7: CRColors2.strokeLightDarkLight7.dark,
      strokeLightDarkLight8: CRColors2.strokeLightDarkLight8.dark,
      strokeLightDarkDark1: CRColors2.strokeLightDarkDark1.dark,
      strokeLightDarkDark2: CRColors2.strokeLightDarkDark2.dark,
      strokeLightDarkDark3: CRColors2.strokeLightDarkDark3.dark,
      strokeLightDarkDark5: CRColors2.strokeLightDarkDark5.dark,
      strokeLightDarkDark4: CRColors2.strokeLightDarkDark4.dark,
      strokeLightDarkDark7: CRColors2.strokeLightDarkDark7.dark,
      strokeLightDarkDark8: CRColors2.strokeLightDarkDark8.dark,
      surfaceBackgroundBackgroundGrey: CRColors2.surfaceBackgroundBackgroundGrey.dark,
      surfaceTagSolidDefaultGrey600: CRColors2.surfaceTagSolidDefaultGrey600.dark,
      surfaceTagInvertedDefaultLight: CRColors2.surfaceTagInvertedDefaultLight.dark,
      surfaceTagInvertedInfoLight: CRColors2.surfaceTagInvertedInfoLight.dark,
      surfaceTagInvertedSuccessLight: CRColors2.surfaceTagInvertedSuccessLight.dark,
      surfaceTagInvertedWarningLight: CRColors2.surfaceTagInvertedWarningLight.dark,
      surfaceTagInvertedErrorLight: CRColors2.surfaceTagInvertedErrorLight.dark,
    );
  }

  @override
  CRThemes copyWith({
    Color? textGeneralBrand,
    Color? textGreyscale900,
    Color? textGreyscale800,
    Color? textGreyscale700,
    Color? textGreyscale600,
    Color? textGreyscale500,
    Color? textGreyscale400,
    Color? textGreyscale300,
    Color? textGreyscale200,
    Color? textGreyscale100,
    Color? textGreyscale50,
    Color? textGeneralWhite,
    Color? textGeneralBlack,
    Color? textAlertsStatusSuccess,
    Color? textAlertsStatusInfo,
    Color? textAlertsStatusWarning,
    Color? textAlertsStatusError,
    Color? surfaceGeneralBrand,
    Color? surfaceGeneralWhite,
    Color? surfaceGeneralBlack,
    Color? surfaceAlertsStatusSuccess,
    Color? surfaceAlertsStatusInfo,
    Color? surfaceAlertsStatusWarning,
    Color? surfaceAlertsStatusError,
    Color? surfaceAlertsStatusLightDisabled,
    Color? surfaceAlertsStatusDarkDisabled,
    Color? surfaceAlertsStatusButtonDisabled,
    Color? surfaceGreyscale900,
    Color? surfaceGreyscale800,
    Color? surfaceGreyscale700,
    Color? surfaceGreyscale600,
    Color? surfaceGreyscale500,
    Color? surfaceGreyscale400,
    Color? surfaceGreyscale300,
    Color? surfaceGreyscale200,
    Color? surfaceGreyscale100,
    Color? surfaceGreyscale50,
    Color? surfaceLightDarkDark1,
    Color? surfaceLightDarkDark2,
    Color? surfaceLightDarkDark3,
    Color? surfaceLightDarkDark6,
    Color? surfaceLightDarkDark7,
    Color? surfaceBackgroundBackgroundTeal,
    Color? surfaceBackgroundBackgroundPurple,
    Color? surfaceBackgroundBackgroundRed,
    Color? surfaceBackgroundBackgroundBlue,
    Color? surfaceBackgroundBackgroundGreen,
    Color? surfaceBackgroundBackgroundBrown,
    Color? surfaceBackgroundBackgroundYellow,
    Color? surfaceBackgroundBackgroundOrange,
    Color? surfaceTransparentTransparentTeal,
    Color? surfaceTransparentTransparentPurple,
    Color? surfaceTransparentTransparentRed,
    Color? surfaceTransparentTransparentBlue,
    Color? surfaceTransparentTransparentGreen,
    Color? surfaceTransparentTransparentBrown,
    Color? surfaceTransparentTransparentYellow,
    Color? surfaceTransparentTransparentOrange,
    Color? strokeGeneralBrand,
    Color? strokeGreyscaleGreyscale300,
    Color? strokeGreyscaleGreyscale200,
    Color? strokeGreyscaleGreyscale100,
    Color? strokeGreyscaleGreyscale50,
    Color? strokeGeneralWhite,
    Color? strokeGeneralBlack,
    Color? strokeAlertsStatusLightDisabled,
    Color? strokeAlertsStatusDarkDisabled,
    Color? strokeAlertsStatusButtonDisabled,
    Color? strokeGreyscaleGreyscale900,
    Color? strokeGreyscaleGreyscale800,
    Color? strokeGreyscaleGreyscale700,
    Color? strokeGreyscaleGreyscale600,
    Color? strokeGreyscaleGreyscale500,
    Color? strokeGreyscaleGreyscale400,
    Color? strokeAlertsStatusSuccess,
    Color? strokeAlertsStatusInfo,
    Color? strokeAlertsStatusWarning,
    Color? strokeAlertsStatusError,
    Color? strokeBorderSingleStrokeBorderLight,
    Color? strokeBorderFullStrokeLight,
    Color? strokeBorderSingleStrokeDividerLight,
    Color? textButtonsBrand,
    Color? textButtonsWhite,
    Color? textButtonsGreyscale900,
    Color? surfaceButtonsBrand,
    Color? surfaceButtonsButtonLight,
    Color? surfaceButtonsButtonDark,
    Color? surfaceButtonsSocialMediaLight,
    Color? surfaceButtonsSocialMediaDark,
    Color? surfaceButtonsButtonDisabled,
    Color? surfaceButtonsButton50,
    Color? textButtonsSocialMediaLight,
    Color? surfaceButtonsGreyscaleIcon900,
    Color? surfaceButtonsWhiteIcon,
    Color? textButtonsBrandLight,
    Color? textButtonsWhiteDark,
    Color? textButtonsSocialMediaDark,
    Color? surfaceButtonsBrandLight,
    Color? surfaceButtonsWhiteDark,
    Color? strokeBorderSingleStrokeBorderDark,
    Color? strokeBorderSingleStrokeDividerDark,
    Color? strokeBorderFullStrokeDark,
    Color? surfaceComponentsDropdownLight,
    Color? surfaceComponentsDropdownDark,
    Color? surfaceComponentsModalLight,
    Color? surfaceComponentsModalDark,
    Color? surfaceComponentsButtomBarActionLight,
    Color? surfaceComponentsButtomBarActionDark,
    Color? surfaceComponentsGeneralFrameLight,
    Color? surfaceComponentsGeneralFrameDark,
    Color? surfaceAdditionalsOverColorFrameLight,
    Color? surfaceComponentsDropdownIconLight,
    Color? surfaceComponentsDropdownIconDark,
    Color? surfaceLightDarkLight2,
    Color? surfaceLightDarkLight3,
    Color? surfaceLightDarkLight6,
    Color? surfaceLightDarkLight7,
    Color? surfaceLightDarkLight1,
    Color? surfaceAdditionalsOverColorFrameDark,
    Color? textGeneralTextLight,
    Color? textGeneralTextDark,
    Color? surfaceGeneralSurfaceLight,
    Color? surfaceGeneralSurfaceDark,
    Color? surfaceLightDarkLight8,
    Color? surfaceLightDarkDark8,
    Color? strokeAdditionalsToggle400,
    Color? surfaceLightDarkLight5,
    Color? surfaceLightDarkDark5,
    Color? surfaceComponentsSearchSurfaceLight,
    Color? surfaceComponentsSearchSurfaceDark,
    Color? textComponentsSearchTextLight,
    Color? textComponentsSearchTextDark,
    Color? textComponentsTextFilled,
    Color? surfaceComponentsSurfaceFilled,
    Color? strokeLightDarkLight1,
    Color? strokeLightDarkLight2,
    Color? strokeLightDarkLight3,
    Color? strokeLightDarkLight5,
    Color? strokeLightDarkLight4,
    Color? strokeLightDarkLight7,
    Color? strokeLightDarkLight8,
    Color? strokeLightDarkDark1,
    Color? strokeLightDarkDark2,
    Color? strokeLightDarkDark3,
    Color? strokeLightDarkDark5,
    Color? strokeLightDarkDark4,
    Color? strokeLightDarkDark7,
    Color? strokeLightDarkDark8,
    Color? surfaceBackgroundBackgroundGrey,
    Color? surfaceTagSolidDefaultGrey600,
    Color? surfaceTagInvertedDefaultLight,
    Color? surfaceTagInvertedInfoLight,
    Color? surfaceTagInvertedSuccessLight,
    Color? surfaceTagInvertedWarningLight,
    Color? surfaceTagInvertedErrorLight,
  }) {
    return CRThemes(
      textGeneralBrand: textGeneralBrand ?? this.textGeneralBrand,
      textGreyscale900: textGreyscale900 ?? this.textGreyscale900,
      textGreyscale800: textGreyscale800 ?? this.textGreyscale800,
      textGreyscale700: textGreyscale700 ?? this.textGreyscale700,
      textGreyscale600: textGreyscale600 ?? this.textGreyscale600,
      textGreyscale500: textGreyscale500 ?? this.textGreyscale500,
      textGreyscale400: textGreyscale400 ?? this.textGreyscale400,
      textGreyscale300: textGreyscale300 ?? this.textGreyscale300,
      textGreyscale200: textGreyscale200 ?? this.textGreyscale200,
      textGreyscale100: textGreyscale100 ?? this.textGreyscale100,
      textGreyscale50: textGreyscale50 ?? this.textGreyscale50,
      textGeneralWhite: textGeneralWhite ?? this.textGeneralWhite,
      textGeneralBlack: textGeneralBlack ?? this.textGeneralBlack,
      textAlertsStatusSuccess: textAlertsStatusSuccess ?? this.textAlertsStatusSuccess,
      textAlertsStatusInfo: textAlertsStatusInfo ?? this.textAlertsStatusInfo,
      textAlertsStatusWarning: textAlertsStatusWarning ?? this.textAlertsStatusWarning,
      textAlertsStatusError: textAlertsStatusError ?? this.textAlertsStatusError,
      surfaceGeneralBrand: surfaceGeneralBrand ?? this.surfaceGeneralBrand,
      surfaceGeneralWhite: surfaceGeneralWhite ?? this.surfaceGeneralWhite,
      surfaceGeneralBlack: surfaceGeneralBlack ?? this.surfaceGeneralBlack,
      surfaceAlertsStatusSuccess: surfaceAlertsStatusSuccess ?? this.surfaceAlertsStatusSuccess,
      surfaceAlertsStatusInfo: surfaceAlertsStatusInfo ?? this.surfaceAlertsStatusInfo,
      surfaceAlertsStatusWarning: surfaceAlertsStatusWarning ?? this.surfaceAlertsStatusWarning,
      surfaceAlertsStatusError: surfaceAlertsStatusError ?? this.surfaceAlertsStatusError,
      surfaceAlertsStatusLightDisabled: surfaceAlertsStatusLightDisabled ?? this.surfaceAlertsStatusLightDisabled,
      surfaceAlertsStatusDarkDisabled: surfaceAlertsStatusDarkDisabled ?? this.surfaceAlertsStatusDarkDisabled,
      surfaceAlertsStatusButtonDisabled: surfaceAlertsStatusButtonDisabled ?? this.surfaceAlertsStatusButtonDisabled,
      surfaceGreyscale900: surfaceGreyscale900 ?? this.surfaceGreyscale900,
      surfaceGreyscale800: surfaceGreyscale800 ?? this.surfaceGreyscale800,
      surfaceGreyscale700: surfaceGreyscale700 ?? this.surfaceGreyscale700,
      surfaceGreyscale600: surfaceGreyscale600 ?? this.surfaceGreyscale600,
      surfaceGreyscale500: surfaceGreyscale500 ?? this.surfaceGreyscale500,
      surfaceGreyscale400: surfaceGreyscale400 ?? this.surfaceGreyscale400,
      surfaceGreyscale300: surfaceGreyscale300 ?? this.surfaceGreyscale300,
      surfaceGreyscale200: surfaceGreyscale200 ?? this.surfaceGreyscale200,
      surfaceGreyscale100: surfaceGreyscale100 ?? this.surfaceGreyscale100,
      surfaceGreyscale50: surfaceGreyscale50 ?? this.surfaceGreyscale50,
      surfaceLightDarkDark1: surfaceLightDarkDark1 ?? this.surfaceLightDarkDark1,
      surfaceLightDarkDark2: surfaceLightDarkDark2 ?? this.surfaceLightDarkDark2,
      surfaceLightDarkDark3: surfaceLightDarkDark3 ?? this.surfaceLightDarkDark3,
      surfaceLightDarkDark6: surfaceLightDarkDark6 ?? this.surfaceLightDarkDark6,
      surfaceLightDarkDark7: surfaceLightDarkDark7 ?? this.surfaceLightDarkDark7,
      surfaceBackgroundBackgroundTeal: surfaceBackgroundBackgroundTeal ?? this.surfaceBackgroundBackgroundTeal,
      surfaceBackgroundBackgroundPurple: surfaceBackgroundBackgroundPurple ?? this.surfaceBackgroundBackgroundPurple,
      surfaceBackgroundBackgroundRed: surfaceBackgroundBackgroundRed ?? this.surfaceBackgroundBackgroundRed,
      surfaceBackgroundBackgroundBlue: surfaceBackgroundBackgroundBlue ?? this.surfaceBackgroundBackgroundBlue,
      surfaceBackgroundBackgroundGreen: surfaceBackgroundBackgroundGreen ?? this.surfaceBackgroundBackgroundGreen,
      surfaceBackgroundBackgroundBrown: surfaceBackgroundBackgroundBrown ?? this.surfaceBackgroundBackgroundBrown,
      surfaceBackgroundBackgroundYellow: surfaceBackgroundBackgroundYellow ?? this.surfaceBackgroundBackgroundYellow,
      surfaceBackgroundBackgroundOrange: surfaceBackgroundBackgroundOrange ?? this.surfaceBackgroundBackgroundOrange,
      surfaceTransparentTransparentTeal: surfaceTransparentTransparentTeal ?? this.surfaceTransparentTransparentTeal,
      surfaceTransparentTransparentPurple: surfaceTransparentTransparentPurple ?? this.surfaceTransparentTransparentPurple,
      surfaceTransparentTransparentRed: surfaceTransparentTransparentRed ?? this.surfaceTransparentTransparentRed,
      surfaceTransparentTransparentBlue: surfaceTransparentTransparentBlue ?? this.surfaceTransparentTransparentBlue,
      surfaceTransparentTransparentGreen: surfaceTransparentTransparentGreen ?? this.surfaceTransparentTransparentGreen,
      surfaceTransparentTransparentBrown: surfaceTransparentTransparentBrown ?? this.surfaceTransparentTransparentBrown,
      surfaceTransparentTransparentYellow: surfaceTransparentTransparentYellow ?? this.surfaceTransparentTransparentYellow,
      surfaceTransparentTransparentOrange: surfaceTransparentTransparentOrange ?? this.surfaceTransparentTransparentOrange,
      strokeGeneralBrand: strokeGeneralBrand ?? this.strokeGeneralBrand,
      strokeGreyscaleGreyscale300: strokeGreyscaleGreyscale300 ?? this.strokeGreyscaleGreyscale300,
      strokeGreyscaleGreyscale200: strokeGreyscaleGreyscale200 ?? this.strokeGreyscaleGreyscale200,
      strokeGreyscaleGreyscale100: strokeGreyscaleGreyscale100 ?? this.strokeGreyscaleGreyscale100,
      strokeGreyscaleGreyscale50: strokeGreyscaleGreyscale50 ?? this.strokeGreyscaleGreyscale50,
      strokeGeneralWhite: strokeGeneralWhite ?? this.strokeGeneralWhite,
      strokeGeneralBlack: strokeGeneralBlack ?? this.strokeGeneralBlack,
      strokeAlertsStatusLightDisabled: strokeAlertsStatusLightDisabled ?? this.strokeAlertsStatusLightDisabled,
      strokeAlertsStatusDarkDisabled: strokeAlertsStatusDarkDisabled ?? this.strokeAlertsStatusDarkDisabled,
      strokeAlertsStatusButtonDisabled: strokeAlertsStatusButtonDisabled ?? this.strokeAlertsStatusButtonDisabled,
      strokeGreyscaleGreyscale900: strokeGreyscaleGreyscale900 ?? this.strokeGreyscaleGreyscale900,
      strokeGreyscaleGreyscale800: strokeGreyscaleGreyscale800 ?? this.strokeGreyscaleGreyscale800,
      strokeGreyscaleGreyscale700: strokeGreyscaleGreyscale700 ?? this.strokeGreyscaleGreyscale700,
      strokeGreyscaleGreyscale600: strokeGreyscaleGreyscale600 ?? this.strokeGreyscaleGreyscale600,
      strokeGreyscaleGreyscale500: strokeGreyscaleGreyscale500 ?? this.strokeGreyscaleGreyscale500,
      strokeGreyscaleGreyscale400: strokeGreyscaleGreyscale400 ?? this.strokeGreyscaleGreyscale400,
      strokeAlertsStatusSuccess: strokeAlertsStatusSuccess ?? this.strokeAlertsStatusSuccess,
      strokeAlertsStatusInfo: strokeAlertsStatusInfo ?? this.strokeAlertsStatusInfo,
      strokeAlertsStatusWarning: strokeAlertsStatusWarning ?? this.strokeAlertsStatusWarning,
      strokeAlertsStatusError: strokeAlertsStatusError ?? this.strokeAlertsStatusError,
      strokeBorderSingleStrokeBorderLight: strokeBorderSingleStrokeBorderLight ?? this.strokeBorderSingleStrokeBorderLight,
      strokeBorderFullStrokeLight: strokeBorderFullStrokeLight ?? this.strokeBorderFullStrokeLight,
      strokeBorderSingleStrokeDividerLight: strokeBorderSingleStrokeDividerLight ?? this.strokeBorderSingleStrokeDividerLight,
      textButtonsBrand: textButtonsBrand ?? this.textButtonsBrand,
      textButtonsWhite: textButtonsWhite ?? this.textButtonsWhite,
      textButtonsGreyscale900: textButtonsGreyscale900 ?? this.textButtonsGreyscale900,
      surfaceButtonsBrand: surfaceButtonsBrand ?? this.surfaceButtonsBrand,
      surfaceButtonsButtonLight: surfaceButtonsButtonLight ?? this.surfaceButtonsButtonLight,
      surfaceButtonsButtonDark: surfaceButtonsButtonDark ?? this.surfaceButtonsButtonDark,
      surfaceButtonsSocialMediaLight: surfaceButtonsSocialMediaLight ?? this.surfaceButtonsSocialMediaLight,
      surfaceButtonsSocialMediaDark: surfaceButtonsSocialMediaDark ?? this.surfaceButtonsSocialMediaDark,
      surfaceButtonsButtonDisabled: surfaceButtonsButtonDisabled ?? this.surfaceButtonsButtonDisabled,
      surfaceButtonsButton50: surfaceButtonsButton50 ?? this.surfaceButtonsButton50,
      textButtonsSocialMediaLight: textButtonsSocialMediaLight ?? this.textButtonsSocialMediaLight,
      surfaceButtonsGreyscaleIcon900: surfaceButtonsGreyscaleIcon900 ?? this.surfaceButtonsGreyscaleIcon900,
      surfaceButtonsWhiteIcon: surfaceButtonsWhiteIcon ?? this.surfaceButtonsWhiteIcon,
      textButtonsBrandLight: textButtonsBrandLight ?? this.textButtonsBrandLight,
      textButtonsWhiteDark: textButtonsWhiteDark ?? this.textButtonsWhiteDark,
      textButtonsSocialMediaDark: textButtonsSocialMediaDark ?? this.textButtonsSocialMediaDark,
      surfaceButtonsBrandLight: surfaceButtonsBrandLight ?? this.surfaceButtonsBrandLight,
      surfaceButtonsWhiteDark: surfaceButtonsWhiteDark ?? this.surfaceButtonsWhiteDark,
      strokeBorderSingleStrokeBorderDark: strokeBorderSingleStrokeBorderDark ?? this.strokeBorderSingleStrokeBorderDark,
      strokeBorderSingleStrokeDividerDark: strokeBorderSingleStrokeDividerDark ?? this.strokeBorderSingleStrokeDividerDark,
      strokeBorderFullStrokeDark: strokeBorderFullStrokeDark ?? this.strokeBorderFullStrokeDark,
      surfaceComponentsDropdownLight: surfaceComponentsDropdownLight ?? this.surfaceComponentsDropdownLight,
      surfaceComponentsDropdownDark: surfaceComponentsDropdownDark ?? this.surfaceComponentsDropdownDark,
      surfaceComponentsModalLight: surfaceComponentsModalLight ?? this.surfaceComponentsModalLight,
      surfaceComponentsModalDark: surfaceComponentsModalDark ?? this.surfaceComponentsModalDark,
      surfaceComponentsButtomBarActionLight: surfaceComponentsButtomBarActionLight ?? this.surfaceComponentsButtomBarActionLight,
      surfaceComponentsButtomBarActionDark: surfaceComponentsButtomBarActionDark ?? this.surfaceComponentsButtomBarActionDark,
      surfaceComponentsGeneralFrameLight: surfaceComponentsGeneralFrameLight ?? this.surfaceComponentsGeneralFrameLight,
      surfaceComponentsGeneralFrameDark: surfaceComponentsGeneralFrameDark ?? this.surfaceComponentsGeneralFrameDark,
      surfaceAdditionalsOverColorFrameLight: surfaceAdditionalsOverColorFrameLight ?? this.surfaceAdditionalsOverColorFrameLight,
      surfaceComponentsDropdownIconLight: surfaceComponentsDropdownIconLight ?? this.surfaceComponentsDropdownIconLight,
      surfaceComponentsDropdownIconDark: surfaceComponentsDropdownIconDark ?? this.surfaceComponentsDropdownIconDark,
      surfaceLightDarkLight2: surfaceLightDarkLight2 ?? this.surfaceLightDarkLight2,
      surfaceLightDarkLight3: surfaceLightDarkLight3 ?? this.surfaceLightDarkLight3,
      surfaceLightDarkLight6: surfaceLightDarkLight6 ?? this.surfaceLightDarkLight6,
      surfaceLightDarkLight7: surfaceLightDarkLight7 ?? this.surfaceLightDarkLight7,
      surfaceLightDarkLight1: surfaceLightDarkLight1 ?? this.surfaceLightDarkLight1,
      surfaceAdditionalsOverColorFrameDark: surfaceAdditionalsOverColorFrameDark ?? this.surfaceAdditionalsOverColorFrameDark,
      textGeneralTextLight: textGeneralTextLight ?? this.textGeneralTextLight,
      textGeneralTextDark: textGeneralTextDark ?? this.textGeneralTextDark,
      surfaceGeneralSurfaceLight: surfaceGeneralSurfaceLight ?? this.surfaceGeneralSurfaceLight,
      surfaceGeneralSurfaceDark: surfaceGeneralSurfaceDark ?? this.surfaceGeneralSurfaceDark,
      surfaceLightDarkLight8: surfaceLightDarkLight8 ?? this.surfaceLightDarkLight8,
      surfaceLightDarkDark8: surfaceLightDarkDark8 ?? this.surfaceLightDarkDark8,
      strokeAdditionalsToggle400: strokeAdditionalsToggle400 ?? this.strokeAdditionalsToggle400,
      surfaceLightDarkLight5: surfaceLightDarkLight5 ?? this.surfaceLightDarkLight5,
      surfaceLightDarkDark5: surfaceLightDarkDark5 ?? this.surfaceLightDarkDark5,
      surfaceComponentsSearchSurfaceLight: surfaceComponentsSearchSurfaceLight ?? this.surfaceComponentsSearchSurfaceLight,
      surfaceComponentsSearchSurfaceDark: surfaceComponentsSearchSurfaceDark ?? this.surfaceComponentsSearchSurfaceDark,
      textComponentsSearchTextLight: textComponentsSearchTextLight ?? this.textComponentsSearchTextLight,
      textComponentsSearchTextDark: textComponentsSearchTextDark ?? this.textComponentsSearchTextDark,
      textComponentsTextFilled: textComponentsTextFilled ?? this.textComponentsTextFilled,
      surfaceComponentsSurfaceFilled: surfaceComponentsSurfaceFilled ?? this.surfaceComponentsSurfaceFilled,
      strokeLightDarkLight1: strokeLightDarkLight1 ?? this.strokeLightDarkLight1,
      strokeLightDarkLight2: strokeLightDarkLight2 ?? this.strokeLightDarkLight2,
      strokeLightDarkLight3: strokeLightDarkLight3 ?? this.strokeLightDarkLight3,
      strokeLightDarkLight5: strokeLightDarkLight5 ?? this.strokeLightDarkLight5,
      strokeLightDarkLight4: strokeLightDarkLight4 ?? this.strokeLightDarkLight4,
      strokeLightDarkLight7: strokeLightDarkLight7 ?? this.strokeLightDarkLight7,
      strokeLightDarkLight8: strokeLightDarkLight8 ?? this.strokeLightDarkLight8,
      strokeLightDarkDark1: strokeLightDarkDark1 ?? this.strokeLightDarkDark1,
      strokeLightDarkDark2: strokeLightDarkDark2 ?? this.strokeLightDarkDark2,
      strokeLightDarkDark3: strokeLightDarkDark3 ?? this.strokeLightDarkDark3,
      strokeLightDarkDark5: strokeLightDarkDark5 ?? this.strokeLightDarkDark5,
      strokeLightDarkDark4: strokeLightDarkDark4 ?? this.strokeLightDarkDark4,
      strokeLightDarkDark7: strokeLightDarkDark7 ?? this.strokeLightDarkDark7,
      strokeLightDarkDark8: strokeLightDarkDark8 ?? this.strokeLightDarkDark8,
      surfaceBackgroundBackgroundGrey: surfaceBackgroundBackgroundGrey ?? this.surfaceBackgroundBackgroundGrey,
      surfaceTagSolidDefaultGrey600: surfaceTagSolidDefaultGrey600 ?? this.surfaceTagSolidDefaultGrey600,
      surfaceTagInvertedDefaultLight: surfaceTagInvertedDefaultLight ?? this.surfaceTagInvertedDefaultLight,
      surfaceTagInvertedInfoLight: surfaceTagInvertedInfoLight ?? this.surfaceTagInvertedInfoLight,
      surfaceTagInvertedSuccessLight: surfaceTagInvertedSuccessLight ?? this.surfaceTagInvertedSuccessLight,
      surfaceTagInvertedWarningLight: surfaceTagInvertedWarningLight ?? this.surfaceTagInvertedWarningLight,
      surfaceTagInvertedErrorLight: surfaceTagInvertedErrorLight ?? this.surfaceTagInvertedErrorLight,
    );
  }

  @override
  CRThemes lerp(ThemeExtension<CRThemes>? other, double t) {
    if (other is! CRThemes) {
      return this;
    }
    return CRThemes(
      textGeneralBrand: Color.lerp(textGeneralBrand, other.textGeneralBrand, t)!,
      textGreyscale900: Color.lerp(textGreyscale900, other.textGreyscale900, t)!,
      textGreyscale800: Color.lerp(textGreyscale800, other.textGreyscale800, t)!,
      textGreyscale700: Color.lerp(textGreyscale700, other.textGreyscale700, t)!,
      textGreyscale600: Color.lerp(textGreyscale600, other.textGreyscale600, t)!,
      textGreyscale500: Color.lerp(textGreyscale500, other.textGreyscale500, t)!,
      textGreyscale400: Color.lerp(textGreyscale400, other.textGreyscale400, t)!,
      textGreyscale300: Color.lerp(textGreyscale300, other.textGreyscale300, t)!,
      textGreyscale200: Color.lerp(textGreyscale200, other.textGreyscale200, t)!,
      textGreyscale100: Color.lerp(textGreyscale100, other.textGreyscale100, t)!,
      textGreyscale50: Color.lerp(textGreyscale50, other.textGreyscale50, t)!,
      textGeneralWhite: Color.lerp(textGeneralWhite, other.textGeneralWhite, t)!,
      textGeneralBlack: Color.lerp(textGeneralBlack, other.textGeneralBlack, t)!,
      textAlertsStatusSuccess: Color.lerp(textAlertsStatusSuccess, other.textAlertsStatusSuccess, t)!,
      textAlertsStatusInfo: Color.lerp(textAlertsStatusInfo, other.textAlertsStatusInfo, t)!,
      textAlertsStatusWarning: Color.lerp(textAlertsStatusWarning, other.textAlertsStatusWarning, t)!,
      textAlertsStatusError: Color.lerp(textAlertsStatusError, other.textAlertsStatusError, t)!,
      surfaceGeneralBrand: Color.lerp(surfaceGeneralBrand, other.surfaceGeneralBrand, t)!,
      surfaceGeneralWhite: Color.lerp(surfaceGeneralWhite, other.surfaceGeneralWhite, t)!,
      surfaceGeneralBlack: Color.lerp(surfaceGeneralBlack, other.surfaceGeneralBlack, t)!,
      surfaceAlertsStatusSuccess: Color.lerp(surfaceAlertsStatusSuccess, other.surfaceAlertsStatusSuccess, t)!,
      surfaceAlertsStatusInfo: Color.lerp(surfaceAlertsStatusInfo, other.surfaceAlertsStatusInfo, t)!,
      surfaceAlertsStatusWarning: Color.lerp(surfaceAlertsStatusWarning, other.surfaceAlertsStatusWarning, t)!,
      surfaceAlertsStatusError: Color.lerp(surfaceAlertsStatusError, other.surfaceAlertsStatusError, t)!,
      surfaceAlertsStatusLightDisabled: Color.lerp(surfaceAlertsStatusLightDisabled, other.surfaceAlertsStatusLightDisabled, t)!,
      surfaceAlertsStatusDarkDisabled: Color.lerp(surfaceAlertsStatusDarkDisabled, other.surfaceAlertsStatusDarkDisabled, t)!,
      surfaceAlertsStatusButtonDisabled: Color.lerp(surfaceAlertsStatusButtonDisabled, other.surfaceAlertsStatusButtonDisabled, t)!,
      surfaceGreyscale900: Color.lerp(surfaceGreyscale900, other.surfaceGreyscale900, t)!,
      surfaceGreyscale800: Color.lerp(surfaceGreyscale800, other.surfaceGreyscale800, t)!,
      surfaceGreyscale700: Color.lerp(surfaceGreyscale700, other.surfaceGreyscale700, t)!,
      surfaceGreyscale600: Color.lerp(surfaceGreyscale600, other.surfaceGreyscale600, t)!,
      surfaceGreyscale500: Color.lerp(surfaceGreyscale500, other.surfaceGreyscale500, t)!,
      surfaceGreyscale400: Color.lerp(surfaceGreyscale400, other.surfaceGreyscale400, t)!,
      surfaceGreyscale300: Color.lerp(surfaceGreyscale300, other.surfaceGreyscale300, t)!,
      surfaceGreyscale200: Color.lerp(surfaceGreyscale200, other.surfaceGreyscale200, t)!,
      surfaceGreyscale100: Color.lerp(surfaceGreyscale100, other.surfaceGreyscale100, t)!,
      surfaceGreyscale50: Color.lerp(surfaceGreyscale50, other.surfaceGreyscale50, t)!,
      surfaceLightDarkDark1: Color.lerp(surfaceLightDarkDark1, other.surfaceLightDarkDark1, t)!,
      surfaceLightDarkDark2: Color.lerp(surfaceLightDarkDark2, other.surfaceLightDarkDark2, t)!,
      surfaceLightDarkDark3: Color.lerp(surfaceLightDarkDark3, other.surfaceLightDarkDark3, t)!,
      surfaceLightDarkDark6: Color.lerp(surfaceLightDarkDark6, other.surfaceLightDarkDark6, t)!,
      surfaceLightDarkDark7: Color.lerp(surfaceLightDarkDark7, other.surfaceLightDarkDark7, t)!,
      surfaceBackgroundBackgroundTeal: Color.lerp(surfaceBackgroundBackgroundTeal, other.surfaceBackgroundBackgroundTeal, t)!,
      surfaceBackgroundBackgroundPurple: Color.lerp(surfaceBackgroundBackgroundPurple, other.surfaceBackgroundBackgroundPurple, t)!,
      surfaceBackgroundBackgroundRed: Color.lerp(surfaceBackgroundBackgroundRed, other.surfaceBackgroundBackgroundRed, t)!,
      surfaceBackgroundBackgroundBlue: Color.lerp(surfaceBackgroundBackgroundBlue, other.surfaceBackgroundBackgroundBlue, t)!,
      surfaceBackgroundBackgroundGreen: Color.lerp(surfaceBackgroundBackgroundGreen, other.surfaceBackgroundBackgroundGreen, t)!,
      surfaceBackgroundBackgroundBrown: Color.lerp(surfaceBackgroundBackgroundBrown, other.surfaceBackgroundBackgroundBrown, t)!,
      surfaceBackgroundBackgroundYellow: Color.lerp(surfaceBackgroundBackgroundYellow, other.surfaceBackgroundBackgroundYellow, t)!,
      surfaceBackgroundBackgroundOrange: Color.lerp(surfaceBackgroundBackgroundOrange, other.surfaceBackgroundBackgroundOrange, t)!,
      surfaceTransparentTransparentTeal: Color.lerp(surfaceTransparentTransparentTeal, other.surfaceTransparentTransparentTeal, t)!,
      surfaceTransparentTransparentPurple: Color.lerp(surfaceTransparentTransparentPurple, other.surfaceTransparentTransparentPurple, t)!,
      surfaceTransparentTransparentRed: Color.lerp(surfaceTransparentTransparentRed, other.surfaceTransparentTransparentRed, t)!,
      surfaceTransparentTransparentBlue: Color.lerp(surfaceTransparentTransparentBlue, other.surfaceTransparentTransparentBlue, t)!,
      surfaceTransparentTransparentGreen: Color.lerp(surfaceTransparentTransparentGreen, other.surfaceTransparentTransparentGreen, t)!,
      surfaceTransparentTransparentBrown: Color.lerp(surfaceTransparentTransparentBrown, other.surfaceTransparentTransparentBrown, t)!,
      surfaceTransparentTransparentYellow: Color.lerp(surfaceTransparentTransparentYellow, other.surfaceTransparentTransparentYellow, t)!,
      surfaceTransparentTransparentOrange: Color.lerp(surfaceTransparentTransparentOrange, other.surfaceTransparentTransparentOrange, t)!,
      strokeGeneralBrand: Color.lerp(strokeGeneralBrand, other.strokeGeneralBrand, t)!,
      strokeGreyscaleGreyscale300: Color.lerp(strokeGreyscaleGreyscale300, other.strokeGreyscaleGreyscale300, t)!,
      strokeGreyscaleGreyscale200: Color.lerp(strokeGreyscaleGreyscale200, other.strokeGreyscaleGreyscale200, t)!,
      strokeGreyscaleGreyscale100: Color.lerp(strokeGreyscaleGreyscale100, other.strokeGreyscaleGreyscale100, t)!,
      strokeGreyscaleGreyscale50: Color.lerp(strokeGreyscaleGreyscale50, other.strokeGreyscaleGreyscale50, t)!,
      strokeGeneralWhite: Color.lerp(strokeGeneralWhite, other.strokeGeneralWhite, t)!,
      strokeGeneralBlack: Color.lerp(strokeGeneralBlack, other.strokeGeneralBlack, t)!,
      strokeAlertsStatusLightDisabled: Color.lerp(strokeAlertsStatusLightDisabled, other.strokeAlertsStatusLightDisabled, t)!,
      strokeAlertsStatusDarkDisabled: Color.lerp(strokeAlertsStatusDarkDisabled, other.strokeAlertsStatusDarkDisabled, t)!,
      strokeAlertsStatusButtonDisabled: Color.lerp(strokeAlertsStatusButtonDisabled, other.strokeAlertsStatusButtonDisabled, t)!,
      strokeGreyscaleGreyscale900: Color.lerp(strokeGreyscaleGreyscale900, other.strokeGreyscaleGreyscale900, t)!,
      strokeGreyscaleGreyscale800: Color.lerp(strokeGreyscaleGreyscale800, other.strokeGreyscaleGreyscale800, t)!,
      strokeGreyscaleGreyscale700: Color.lerp(strokeGreyscaleGreyscale700, other.strokeGreyscaleGreyscale700, t)!,
      strokeGreyscaleGreyscale600: Color.lerp(strokeGreyscaleGreyscale600, other.strokeGreyscaleGreyscale600, t)!,
      strokeGreyscaleGreyscale500: Color.lerp(strokeGreyscaleGreyscale500, other.strokeGreyscaleGreyscale500, t)!,
      strokeGreyscaleGreyscale400: Color.lerp(strokeGreyscaleGreyscale400, other.strokeGreyscaleGreyscale400, t)!,
      strokeAlertsStatusSuccess: Color.lerp(strokeAlertsStatusSuccess, other.strokeAlertsStatusSuccess, t)!,
      strokeAlertsStatusInfo: Color.lerp(strokeAlertsStatusInfo, other.strokeAlertsStatusInfo, t)!,
      strokeAlertsStatusWarning: Color.lerp(strokeAlertsStatusWarning, other.strokeAlertsStatusWarning, t)!,
      strokeAlertsStatusError: Color.lerp(strokeAlertsStatusError, other.strokeAlertsStatusError, t)!,
      strokeBorderSingleStrokeBorderLight: Color.lerp(strokeBorderSingleStrokeBorderLight, other.strokeBorderSingleStrokeBorderLight, t)!,
      strokeBorderFullStrokeLight: Color.lerp(strokeBorderFullStrokeLight, other.strokeBorderFullStrokeLight, t)!,
      strokeBorderSingleStrokeDividerLight: Color.lerp(strokeBorderSingleStrokeDividerLight, other.strokeBorderSingleStrokeDividerLight, t)!,
      textButtonsBrand: Color.lerp(textButtonsBrand, other.textButtonsBrand, t)!,
      textButtonsWhite: Color.lerp(textButtonsWhite, other.textButtonsWhite, t)!,
      textButtonsGreyscale900: Color.lerp(textButtonsGreyscale900, other.textButtonsGreyscale900, t)!,
      surfaceButtonsBrand: Color.lerp(surfaceButtonsBrand, other.surfaceButtonsBrand, t)!,
      surfaceButtonsButtonLight: Color.lerp(surfaceButtonsButtonLight, other.surfaceButtonsButtonLight, t)!,
      surfaceButtonsButtonDark: Color.lerp(surfaceButtonsButtonDark, other.surfaceButtonsButtonDark, t)!,
      surfaceButtonsSocialMediaLight: Color.lerp(surfaceButtonsSocialMediaLight, other.surfaceButtonsSocialMediaLight, t)!,
      surfaceButtonsSocialMediaDark: Color.lerp(surfaceButtonsSocialMediaDark, other.surfaceButtonsSocialMediaDark, t)!,
      surfaceButtonsButtonDisabled: Color.lerp(surfaceButtonsButtonDisabled, other.surfaceButtonsButtonDisabled, t)!,
      surfaceButtonsButton50: Color.lerp(surfaceButtonsButton50, other.surfaceButtonsButton50, t)!,
      textButtonsSocialMediaLight: Color.lerp(textButtonsSocialMediaLight, other.textButtonsSocialMediaLight, t)!,
      surfaceButtonsGreyscaleIcon900: Color.lerp(surfaceButtonsGreyscaleIcon900, other.surfaceButtonsGreyscaleIcon900, t)!,
      surfaceButtonsWhiteIcon: Color.lerp(surfaceButtonsWhiteIcon, other.surfaceButtonsWhiteIcon, t)!,
      textButtonsBrandLight: Color.lerp(textButtonsBrandLight, other.textButtonsBrandLight, t)!,
      textButtonsWhiteDark: Color.lerp(textButtonsWhiteDark, other.textButtonsWhiteDark, t)!,
      textButtonsSocialMediaDark: Color.lerp(textButtonsSocialMediaDark, other.textButtonsSocialMediaDark, t)!,
      surfaceButtonsBrandLight: Color.lerp(surfaceButtonsBrandLight, other.surfaceButtonsBrandLight, t)!,
      surfaceButtonsWhiteDark: Color.lerp(surfaceButtonsWhiteDark, other.surfaceButtonsWhiteDark, t)!,
      strokeBorderSingleStrokeBorderDark: Color.lerp(strokeBorderSingleStrokeBorderDark, other.strokeBorderSingleStrokeBorderDark, t)!,
      strokeBorderSingleStrokeDividerDark: Color.lerp(strokeBorderSingleStrokeDividerDark, other.strokeBorderSingleStrokeDividerDark, t)!,
      strokeBorderFullStrokeDark: Color.lerp(strokeBorderFullStrokeDark, other.strokeBorderFullStrokeDark, t)!,
      surfaceComponentsDropdownLight: Color.lerp(surfaceComponentsDropdownLight, other.surfaceComponentsDropdownLight, t)!,
      surfaceComponentsDropdownDark: Color.lerp(surfaceComponentsDropdownDark, other.surfaceComponentsDropdownDark, t)!,
      surfaceComponentsModalLight: Color.lerp(surfaceComponentsModalLight, other.surfaceComponentsModalLight, t)!,
      surfaceComponentsModalDark: Color.lerp(surfaceComponentsModalDark, other.surfaceComponentsModalDark, t)!,
      surfaceComponentsButtomBarActionLight: Color.lerp(surfaceComponentsButtomBarActionLight, other.surfaceComponentsButtomBarActionLight, t)!,
      surfaceComponentsButtomBarActionDark: Color.lerp(surfaceComponentsButtomBarActionDark, other.surfaceComponentsButtomBarActionDark, t)!,
      surfaceComponentsGeneralFrameLight: Color.lerp(surfaceComponentsGeneralFrameLight, other.surfaceComponentsGeneralFrameLight, t)!,
      surfaceComponentsGeneralFrameDark: Color.lerp(surfaceComponentsGeneralFrameDark, other.surfaceComponentsGeneralFrameDark, t)!,
      surfaceAdditionalsOverColorFrameLight: Color.lerp(surfaceAdditionalsOverColorFrameLight, other.surfaceAdditionalsOverColorFrameLight, t)!,
      surfaceComponentsDropdownIconLight: Color.lerp(surfaceComponentsDropdownIconLight, other.surfaceComponentsDropdownIconLight, t)!,
      surfaceComponentsDropdownIconDark: Color.lerp(surfaceComponentsDropdownIconDark, other.surfaceComponentsDropdownIconDark, t)!,
      surfaceLightDarkLight2: Color.lerp(surfaceLightDarkLight2, other.surfaceLightDarkLight2, t)!,
      surfaceLightDarkLight3: Color.lerp(surfaceLightDarkLight3, other.surfaceLightDarkLight3, t)!,
      surfaceLightDarkLight6: Color.lerp(surfaceLightDarkLight6, other.surfaceLightDarkLight6, t)!,
      surfaceLightDarkLight7: Color.lerp(surfaceLightDarkLight7, other.surfaceLightDarkLight7, t)!,
      surfaceLightDarkLight1: Color.lerp(surfaceLightDarkLight1, other.surfaceLightDarkLight1, t)!,
      surfaceAdditionalsOverColorFrameDark: Color.lerp(surfaceAdditionalsOverColorFrameDark, other.surfaceAdditionalsOverColorFrameDark, t)!,
      textGeneralTextLight: Color.lerp(textGeneralTextLight, other.textGeneralTextLight, t)!,
      textGeneralTextDark: Color.lerp(textGeneralTextDark, other.textGeneralTextDark, t)!,
      surfaceGeneralSurfaceLight: Color.lerp(surfaceGeneralSurfaceLight, other.surfaceGeneralSurfaceLight, t)!,
      surfaceGeneralSurfaceDark: Color.lerp(surfaceGeneralSurfaceDark, other.surfaceGeneralSurfaceDark, t)!,
      surfaceLightDarkLight8: Color.lerp(surfaceLightDarkLight8, other.surfaceLightDarkLight8, t)!,
      surfaceLightDarkDark8: Color.lerp(surfaceLightDarkDark8, other.surfaceLightDarkDark8, t)!,
      strokeAdditionalsToggle400: Color.lerp(strokeAdditionalsToggle400, other.strokeAdditionalsToggle400, t)!,
      surfaceLightDarkLight5: Color.lerp(surfaceLightDarkLight5, other.surfaceLightDarkLight5, t)!,
      surfaceLightDarkDark5: Color.lerp(surfaceLightDarkDark5, other.surfaceLightDarkDark5, t)!,
      surfaceComponentsSearchSurfaceLight: Color.lerp(surfaceComponentsSearchSurfaceLight, other.surfaceComponentsSearchSurfaceLight, t)!,
      surfaceComponentsSearchSurfaceDark: Color.lerp(surfaceComponentsSearchSurfaceDark, other.surfaceComponentsSearchSurfaceDark, t)!,
      textComponentsSearchTextLight: Color.lerp(textComponentsSearchTextLight, other.textComponentsSearchTextLight, t)!,
      textComponentsSearchTextDark: Color.lerp(textComponentsSearchTextDark, other.textComponentsSearchTextDark, t)!,
      textComponentsTextFilled: Color.lerp(textComponentsTextFilled, other.textComponentsTextFilled, t)!,
      surfaceComponentsSurfaceFilled: Color.lerp(surfaceComponentsSurfaceFilled, other.surfaceComponentsSurfaceFilled, t)!,
      strokeLightDarkLight1: Color.lerp(strokeLightDarkLight1, other.strokeLightDarkLight1, t)!,
      strokeLightDarkLight2: Color.lerp(strokeLightDarkLight2, other.strokeLightDarkLight2, t)!,
      strokeLightDarkLight3: Color.lerp(strokeLightDarkLight3, other.strokeLightDarkLight3, t)!,
      strokeLightDarkLight5: Color.lerp(strokeLightDarkLight5, other.strokeLightDarkLight5, t)!,
      strokeLightDarkLight4: Color.lerp(strokeLightDarkLight4, other.strokeLightDarkLight4, t)!,
      strokeLightDarkLight7: Color.lerp(strokeLightDarkLight7, other.strokeLightDarkLight7, t)!,
      strokeLightDarkLight8: Color.lerp(strokeLightDarkLight8, other.strokeLightDarkLight8, t)!,
      strokeLightDarkDark1: Color.lerp(strokeLightDarkDark1, other.strokeLightDarkDark1, t)!,
      strokeLightDarkDark2: Color.lerp(strokeLightDarkDark2, other.strokeLightDarkDark2, t)!,
      strokeLightDarkDark3: Color.lerp(strokeLightDarkDark3, other.strokeLightDarkDark3, t)!,
      strokeLightDarkDark5: Color.lerp(strokeLightDarkDark5, other.strokeLightDarkDark5, t)!,
      strokeLightDarkDark4: Color.lerp(strokeLightDarkDark4, other.strokeLightDarkDark4, t)!,
      strokeLightDarkDark7: Color.lerp(strokeLightDarkDark7, other.strokeLightDarkDark7, t)!,
      strokeLightDarkDark8: Color.lerp(strokeLightDarkDark8, other.strokeLightDarkDark8, t)!,
      surfaceBackgroundBackgroundGrey: Color.lerp(surfaceBackgroundBackgroundGrey, other.surfaceBackgroundBackgroundGrey, t)!,
      surfaceTagSolidDefaultGrey600: Color.lerp(surfaceTagSolidDefaultGrey600, other.surfaceTagSolidDefaultGrey600, t)!,
      surfaceTagInvertedDefaultLight: Color.lerp(surfaceTagInvertedDefaultLight, other.surfaceTagInvertedDefaultLight, t)!,
      surfaceTagInvertedInfoLight: Color.lerp(surfaceTagInvertedInfoLight, other.surfaceTagInvertedInfoLight, t)!,
      surfaceTagInvertedSuccessLight: Color.lerp(surfaceTagInvertedSuccessLight, other.surfaceTagInvertedSuccessLight, t)!,
      surfaceTagInvertedWarningLight: Color.lerp(surfaceTagInvertedWarningLight, other.surfaceTagInvertedWarningLight, t)!,
      surfaceTagInvertedErrorLight: Color.lerp(surfaceTagInvertedErrorLight, other.surfaceTagInvertedErrorLight, t)!,
    );
  }
}
