// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/local/database/entity/master_country_entity.dart';
import 'data/local/database/entity/master_country_type_entity.dart';
import 'data/local/database/entity/master_degree_entity.dart';
import 'data/local/database/entity/master_funding_type.dart';
import 'data/local/database/entity/master_institution_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 6220939652947771719),
      name: 'MasterCountryEntity',
      lastPropertyId: const obx_int.IdUid(2, 3589334054665432221),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8727727529048081506),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3589334054665432221),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 3169421397745030207),
      name: 'MasterCountryTypeEntity',
      lastPropertyId: const obx_int.IdUid(2, 7327609673402513339),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7727787630245999009),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7327609673402513339),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 4488416915214931699),
      name: 'MasterInstitutionEntity',
      lastPropertyId: const obx_int.IdUid(2, 6520141069570829335),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1438698614216258156),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6520141069570829335),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 8715471644191733671),
      name: 'MasterFundingTypeEntity',
      lastPropertyId: const obx_int.IdUid(3, 1078181946618725794),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4284879293866114226),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2544610693657075376),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1078181946618725794),
            name: 'description',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 270341630204823289),
      name: 'MasterDegreeEntity',
      lastPropertyId: const obx_int.IdUid(3, 761932867701709523),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3338127616737839914),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2216680921631455863),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 761932867701709523),
            name: 'description',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(6, 270341630204823289),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [2635203160353928829],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        5927677665974390758,
        8399151342300733033,
        7315707953441087355
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    MasterCountryEntity: obx_int.EntityDefinition<MasterCountryEntity>(
        model: _entities[0],
        toOneRelations: (MasterCountryEntity object) => [],
        toManyRelations: (MasterCountryEntity object) => {},
        getId: (MasterCountryEntity object) => object.id,
        setId: (MasterCountryEntity object, int id) {
          object.id = id;
        },
        objectToFB: (MasterCountryEntity object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          fbb.startTable(3);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final object = MasterCountryEntity(id: idParam, name: nameParam);

          return object;
        }),
    MasterCountryTypeEntity: obx_int.EntityDefinition<MasterCountryTypeEntity>(
        model: _entities[1],
        toOneRelations: (MasterCountryTypeEntity object) => [],
        toManyRelations: (MasterCountryTypeEntity object) => {},
        getId: (MasterCountryTypeEntity object) => object.id,
        setId: (MasterCountryTypeEntity object, int id) {
          object.id = id;
        },
        objectToFB: (MasterCountryTypeEntity object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          fbb.startTable(3);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = MasterCountryTypeEntity()
            ..id =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4)
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 6);

          return object;
        }),
    MasterInstitutionEntity: obx_int.EntityDefinition<MasterInstitutionEntity>(
        model: _entities[2],
        toOneRelations: (MasterInstitutionEntity object) => [],
        toManyRelations: (MasterInstitutionEntity object) => {},
        getId: (MasterInstitutionEntity object) => object.id,
        setId: (MasterInstitutionEntity object, int id) {
          object.id = id;
        },
        objectToFB: (MasterInstitutionEntity object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          fbb.startTable(3);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final object = MasterInstitutionEntity(id: idParam, name: nameParam);

          return object;
        }),
    MasterFundingTypeEntity: obx_int.EntityDefinition<MasterFundingTypeEntity>(
        model: _entities[3],
        toOneRelations: (MasterFundingTypeEntity object) => [],
        toManyRelations: (MasterFundingTypeEntity object) => {},
        getId: (MasterFundingTypeEntity object) => object.id,
        setId: (MasterFundingTypeEntity object, int id) {
          object.id = id;
        },
        objectToFB: (MasterFundingTypeEntity object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          fbb.startTable(4);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8);
          final object = MasterFundingTypeEntity(
              id: idParam, name: nameParam, description: descriptionParam);

          return object;
        }),
    MasterDegreeEntity: obx_int.EntityDefinition<MasterDegreeEntity>(
        model: _entities[4],
        toOneRelations: (MasterDegreeEntity object) => [],
        toManyRelations: (MasterDegreeEntity object) => {},
        getId: (MasterDegreeEntity object) => object.id,
        setId: (MasterDegreeEntity object, int id) {
          object.id = id;
        },
        objectToFB: (MasterDegreeEntity object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          fbb.startTable(4);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8);
          final object = MasterDegreeEntity(
              id: idParam, name: nameParam, description: descriptionParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MasterCountryEntity] entity fields to define ObjectBox queries.
class MasterCountryEntity_ {
  /// See [MasterCountryEntity.id].
  static final id =
      obx.QueryIntegerProperty<MasterCountryEntity>(_entities[0].properties[0]);

  /// See [MasterCountryEntity.name].
  static final name =
      obx.QueryStringProperty<MasterCountryEntity>(_entities[0].properties[1]);
}

/// [MasterCountryTypeEntity] entity fields to define ObjectBox queries.
class MasterCountryTypeEntity_ {
  /// See [MasterCountryTypeEntity.id].
  static final id = obx.QueryIntegerProperty<MasterCountryTypeEntity>(
      _entities[1].properties[0]);

  /// See [MasterCountryTypeEntity.name].
  static final name = obx.QueryStringProperty<MasterCountryTypeEntity>(
      _entities[1].properties[1]);
}

/// [MasterInstitutionEntity] entity fields to define ObjectBox queries.
class MasterInstitutionEntity_ {
  /// See [MasterInstitutionEntity.id].
  static final id = obx.QueryIntegerProperty<MasterInstitutionEntity>(
      _entities[2].properties[0]);

  /// See [MasterInstitutionEntity.name].
  static final name = obx.QueryStringProperty<MasterInstitutionEntity>(
      _entities[2].properties[1]);
}

/// [MasterFundingTypeEntity] entity fields to define ObjectBox queries.
class MasterFundingTypeEntity_ {
  /// See [MasterFundingTypeEntity.id].
  static final id = obx.QueryIntegerProperty<MasterFundingTypeEntity>(
      _entities[3].properties[0]);

  /// See [MasterFundingTypeEntity.name].
  static final name = obx.QueryStringProperty<MasterFundingTypeEntity>(
      _entities[3].properties[1]);

  /// See [MasterFundingTypeEntity.description].
  static final description = obx.QueryStringProperty<MasterFundingTypeEntity>(
      _entities[3].properties[2]);
}

/// [MasterDegreeEntity] entity fields to define ObjectBox queries.
class MasterDegreeEntity_ {
  /// See [MasterDegreeEntity.id].
  static final id =
      obx.QueryIntegerProperty<MasterDegreeEntity>(_entities[4].properties[0]);

  /// See [MasterDegreeEntity.name].
  static final name =
      obx.QueryStringProperty<MasterDegreeEntity>(_entities[4].properties[1]);

  /// See [MasterDegreeEntity.description].
  static final description =
      obx.QueryStringProperty<MasterDegreeEntity>(_entities[4].properties[2]);
}
